{
 "title": "Space Odyssey",
 "time": { "from": "2025-11-29T20:50:54.563Z", "to": "2025-11-30T08:50:54.563Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Ship Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"log\")\r\n  |> limit(n: 5)"
    }
   ]
  },
  {
   "title": "Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"current_date\")"
    }
   ]
  },
  {
   "title": "Oxygen levels",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"oxygen\")"
    }
   ]
  },
  {
   "title": "Fuel level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"fuel\")"
    }
   ]
  },
  {
   "title": "Hull Integrity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"hull_integrity\")"
    }
   ]
  },
  {
   "title": "Crew Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"crewmates\")"
    }
   ]
  },
  {
   "title": "Story",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"story\")\r\n  |> filter(fn: (r) => r._field == \"next_story_point\")\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n:5)"
    }
   ]
  },
  {
   "title": "Spare Parts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"spare_parts\")"
    }
   ]
  },
  {
   "title": "Water Reserves",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"water\")"
    }
   ]
  },
  {
   "title": "Ammo Reserves",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"ammo\")"
    }
   ]
  },
  {
   "title": "Food Stock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"food\")"
    }
   ]
  },
  {
   "title": "Medical Supplies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"game_metrics\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"ship\")\r\n  |> filter(fn: (r) => r._field == \"medical\")"
    }
   ]
  },
  {
   "title": "Control Panel",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "<div style=\"text-align: center; padding: 20px;\">\n  <a href=\"http://localhost:5000/static/loader.html?action=cook_food\" \n     target=\"_blank\"\n     style=\"\n       background: transparent; \n       border: 2px solid #00ccff; \n       color: #00ccff; \n       padding: 15px 30px; \n       font-family: 'Courier New', monospace; \n       font-weight: bold; \n       text-decoration: none; \n       text-transform: uppercase;\n       display: inline-block;\n       margin: 10px;\n     \"\n    >\n    Cook Food\n  </a>\n\n  <a href=\"http://localhost:5000/static/loader.html?action=spare\" \n     target=\"_blank\"\n     style=\"\n       background: transparent; \n       border: 2px solid #ffA400; \n       color: #ffA400; \n       padding: 15px 30px; \n       font-family: 'Courier New', monospace; \n       font-weight: bold; \n       text-decoration: none; \n       text-transform: uppercase;\n       display: inline-block;\n       margin: 10px;\n     \"\n    >\n    Spare Button\n  </a>\n\n   <a href=\"http://localhost:5000/static/loader.html?action=defend_ship\" \n     target=\"_blank\"\n     style=\"\n       background: transparent; \n       border: 2px solid #ff4444; \n       color: #ff4444; \n       padding: 15px 30px; \n       font-family: 'Courier New', monospace; \n       font-weight: bold; \n       text-decoration: none; \n       text-transform: uppercase;\n       display: inline-block;\n       margin: 10px;\n     \"\n    >\n    Defend Ship\n  </a>\n\n  <a href=\"http://localhost:5000/static/loader.html?action=next_day\" \n     target=\"_blank\"\n     style=\"\n       background: transparent; \n       border: 2px solid #44ff44; \n       color: #44ff44; \n       padding: 15px 30px; \n       font-family: 'Courier New', monospace; \n       font-weight: bold; \n       text-decoration: none; \n       text-transform: uppercase;\n       display: inline-block;\n       margin: 10px;\n     \"\n    >\n    Next Day\n  </a>\n\n  <a href=\"http://localhost:5000/static/loader.html?action=repair_ship\" \n     target=\"_blank\"\n     style=\"\n       background: transparent; \n       border: 2px solid #ff4444; \n       color: #ff4444; \n       padding: 15px 30px; \n       font-family: 'Courier New', monospace; \n       font-weight: bold; \n       text-decoration: none; \n       text-transform: uppercase;\n       display: inline-block;\n       margin: 10px;\n     \"\n    >\n    Repair Ship\n  </a>\n\n  <a href=\"http://localhost:5000/static/loader.html?action=heal_crew\" \n     target=\"_blank\"\n     style=\"\n       background: transparent; \n       border: 2px solid #ffA400; \n       color: #ffA400; \n       padding: 15px 30px; \n       font-family: 'Courier New', monospace; \n       font-weight: bold; \n       text-decoration: none; \n       text-transform: uppercase;\n       display: inline-block;\n       margin: 10px;\n     \"\n    >\n    Heal Crew\n  </a>\n\n  <a href=\"http://localhost:5000/static/loader.html?action=spare\" \n     target=\"_blank\"\n     style=\"\n       background: transparent; \n       border: 2px solid #00ccff; \n       color: #00ccff; \n       padding: 15px 30px; \n       font-family: 'Courier New', monospace; \n       font-weight: bold; \n       text-decoration: none; \n       text-transform: uppercase;\n       display: inline-block;\n       margin: 10px;\n     \"\n    >\n    Spare Button\n  </a>\n</div>"
   }
  }
 ]
}